### PR TITLE
Visual fixes

### LINKED ISSUE #152: Визуальные фиксы
- [ ] подвинуть спиннер
- [x] падинги у ServiceMessage
- [x] убрать скачки "+" и будильника у сообщения
- [x] поднять кнопку "Create сhat"
- [ ] убрать загрузку при тыке на плюс
- [x] hoverы на интерактивных элементах
- [x] выровнять header и searchbar
- [ ] поправить спиннер при загрузке изображений
- [x] поправить иконку "копировать" в информации о беседе

### PR DESCRIPTION
**Pull request by tonyfresher**
Closes #152 #174 #173 #180

### CODE REVIEW

File: client/src/components/ChatList/ChatCreate/index.js [hunk 1]
```diff
@@ -44,10 +48,17 @@ export default class ChatCreate extends Component {
...
-                    onClick={this.buttonClickHandler.bind(this)}
-                    {...disabled}>Create chat
-                </button>
+                <div className={styles.Buttons}>
+                    <button className={styles.CancelButton}
+                        onClick={() => this.cancelButtonClickHandler()}>
+                        <span>Cancel</span>
+                    </button>
+                    <button type="button" className={styles.CreateButton}
+                        onClick={() => this.buttonClickHandler()}
```
Comment (sanyabas) [inline client/src/components/ChatList/ChatCreate/index.js]: `createButtonClickHandler()`
